# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- script: |
     git clone https://github.com/Microsoft/vcpkg.git
     cd vcpkg && git checkout 2021.05.12 && cd ../
     ./vcpkg/bootstrap-vcpkg.sh
     echo "export VCPKG_HOME=$(pwd)/vcpkg" >  vcpkg.env
     echo "export PATH=$PATH:$(pwd)/vcpkg" >>  vcpkg.env
  displayName: 'Install vcpkg'

- script: |
    cat ./vcpkg.env
    source ./vcpkg.env
    echo $PATH
    cmake --version
    python --version
    python run.py
  displayName: 'Run a multi-line script'
